version: '2'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
    - MYSQL_DATABASE=db
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/conf.d:/etc/mysql/conf.d

  web:
    build: 
      context: php
    volumes:
    - ./src:/var/www/html:rw
    ports:
    - 127.0.0.1:8181:80

